// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.time.Duration;
import java.util.*;

public class BoardCreationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private WebDriverWait wait;

    @Before
    public void setUp() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        wait = new WebDriverWait(driver, Duration.ofSeconds(10)); // 10-second timeout
        driver.manage().window().setSize(new Dimension(654, 751));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void boardCreation() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(602, 971));

        wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();

        wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("board_name")))
                .sendKeys("Software Testing");

        wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();

        assertThat(
                wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("h3")))
                        .getText(),
                is("Software Testing")
        );
    }
}