// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NonUserAddTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void nonUserAdd() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(706, 752));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("#\\38-software-security > .inner")).click();
    driver.findElement(By.cssSelector("li > .add-new")).click();
    driver.findElement(By.id("crawljax_member_email")).click();
    driver.findElement(By.id("crawljax_member_email")).sendKeys("bsse1412@iit.du.ac.bd");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".drop-down")).click();
    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("User does not exist"));
  }
}
