// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;


import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.*;


public class PasswordLengthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        driver.manage().window().setSize(new Dimension(654, 751));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void passwordLength() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(602, 743));
        driver.findElement(By.linkText("Create new account")).click();
        driver.findElement(By.id("user_first_name")).click();
        driver.findElement(By.id("user_first_name")).sendKeys("Samdani");
        driver.findElement(By.id("user_last_name")).click();
        driver.findElement(By.id("user_last_name")).sendKeys("Mozumder");
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).sendKeys("bsse1412@iit.du.ac.bd");
        driver.findElement(By.id("user_password_confirmation")).click();
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).sendKeys("1234");
        driver.findElement(By.id("user_password_confirmation")).click();
        driver.findElement(By.id("user_password_confirmation")).sendKeys("1234");
        driver.findElement(By.cssSelector("button")).click();
        assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("should be at least 5 character(s)"));
    }
}
